/* C code for program ch_fsm, generated by snc from ch_fsm.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 17 "ch_fsm.st"
#define PRINTF seqLog
# line 18 "ch_fsm.st"
#define RES_M 0.000077
# line 19 "ch_fsm.st"
#define RES_H 0.000020

/* Variable declarations */
struct seqg_vars {
# line 27 "ch_fsm.st"
	short DAC;
# line 31 "ch_fsm.st"
	short DAC_rdbck;
# line 35 "ch_fsm.st"
	short Park;
# line 40 "ch_fsm.st"
	short Polarity;
# line 44 "ch_fsm.st"
	short flt_mask;
# line 48 "ch_fsm.st"
	short flt_clr;
# line 52 "ch_fsm.st"
	short ps_on_off;
# line 56 "ch_fsm.st"
	short ps_on_off_sts;
# line 60 "ch_fsm.st"
	short ps_on_sts_bip;
# line 64 "ch_fsm.st"
	short ps_on_sts_uni;
# line 68 "ch_fsm.st"
	short on1_cmd;
# line 71 "ch_fsm.st"
	short ch1_en_cmd;
# line 75 "ch_fsm.st"
	short ch2_en_cmd;
# line 79 "ch_fsm.st"
	short ch3_en_cmd;
# line 83 "ch_fsm.st"
	short ch4_en_cmd;
# line 87 "ch_fsm.st"
	short sum_fault;
# line 91 "ch_fsm.st"
	short autozero;
# line 95 "ch_fsm.st"
	double dcct1_adc;
# line 99 "ch_fsm.st"
	double dcct1_ofst;
# line 103 "ch_fsm.st"
	double dcct2_adc;
# line 107 "ch_fsm.st"
	double dcct2_ofst;
# line 111 "ch_fsm.st"
	short mode;
# line 115 "ch_fsm.st"
	double error_adc;
# line 119 "ch_fsm.st"
	double dac_ofst;
# line 123 "ch_fsm.st"
	double scale_factor;
# line 127 "ch_fsm.st"
	short res;
# line 131 "ch_fsm.st"
	short avg_mode;
# line 135 "ch_fsm.st"
	short atzo_sts;
# line 140 "ch_fsm.st"
	string Chan_seq_messages;
# line 143 "ch_fsm.st"
	string atzo_messages;
# line 146 "ch_fsm.st"
	string atzo_dbg1_messages;
# line 149 "ch_fsm.st"
	string atzo_dbg2_messages;
# line 152 "ch_fsm.st"
	string atzo_dbg3_messages;
# line 155 "ch_fsm.st"
	int from_faulted_state;
# line 156 "ch_fsm.st"
	double error_old;
# line 157 "ch_fsm.st"
	double error_new;
# line 158 "ch_fsm.st"
	unsigned int up;
# line 159 "ch_fsm.st"
	int timeout_count;
# line 160 "ch_fsm.st"
	int check_count;
# line 161 "ch_fsm.st"
	int up_vote;
# line 162 "ch_fsm.st"
	int down_vote;
};


/* Function declarations */
# line 24 "ch_fsm.st"
static double fabs(SS_ID seqg_env, double);

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "INIT_1" in state set "OFF_ON_FSM" ******/

/* Event function for state "INIT_1" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_INIT_1(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "INIT_1" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_INIT_1(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 171 "ch_fsm.st"
			seqg_var->flt_mask = 1;
# line 172 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 4/*flt_mask*/, DEFAULT, DEFAULT_TIMEOUT);
# line 173 "ch_fsm.st"
			seqg_var->DAC = 0;
# line 174 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 0/*DAC*/, DEFAULT, DEFAULT_TIMEOUT);
# line 175 "ch_fsm.st"
			seqg_var->ps_on_off_sts = 0;
# line 176 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 7/*ps_on_off_sts*/, DEFAULT, DEFAULT_TIMEOUT);
# line 177 "ch_fsm.st"
			seqg_var->Park = 1;
# line 178 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 2/*Park*/, DEFAULT, DEFAULT_TIMEOUT);
# line 179 "ch_fsm.st"
			seqg_var->on1_cmd = 0;
# line 180 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 10/*on1_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 181 "ch_fsm.st"
			seqg_var->ch1_en_cmd = 1;
# line 182 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 11/*ch1_en_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 183 "ch_fsm.st"
			seqg_var->ch2_en_cmd = 1;
# line 184 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 12/*ch2_en_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 185 "ch_fsm.st"
			seqg_var->ch3_en_cmd = 1;
# line 186 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 13/*ch3_en_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 187 "ch_fsm.st"
			seqg_var->ch4_en_cmd = 1;
# line 188 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 14/*ch4_en_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 189 "ch_fsm.st"
			printf("Initializing OFF_ON_FSM...\n");
# line 190 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "WAIT...1");
# line 191 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "INIT_2" in state set "OFF_ON_FSM" ******/

/* Event function for state "INIT_2" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_INIT_2(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 195 "ch_fsm.st"
	if (seq_delay(seqg_env, 3))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "INIT_2" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_INIT_2(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 196 "ch_fsm.st"
			seqg_var->ch1_en_cmd = 1;
# line 197 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 11/*ch1_en_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 198 "ch_fsm.st"
			seqg_var->ch2_en_cmd = 1;
# line 199 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 12/*ch2_en_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 200 "ch_fsm.st"
			seqg_var->ch3_en_cmd = 1;
# line 201 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 13/*ch3_en_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 202 "ch_fsm.st"
			seqg_var->ch4_en_cmd = 1;
# line 203 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 14/*ch4_en_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 204 "ch_fsm.st"
			seqg_var->flt_mask = 0;
# line 205 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 4/*flt_mask*/, DEFAULT, DEFAULT_TIMEOUT);
# line 206 "ch_fsm.st"
			printf("Initializing OFF_ON_FSM...\n");
# line 207 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "WAIT...2");
# line 208 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "INIT_3" in state set "OFF_ON_FSM" ******/

/* Event function for state "INIT_3" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_INIT_3(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 212 "ch_fsm.st"
	if (seq_delay(seqg_env, 2))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "INIT_3" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_INIT_3(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 213 "ch_fsm.st"
			seqg_var->flt_mask = 1;
# line 214 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 4/*flt_mask*/, DEFAULT, DEFAULT_TIMEOUT);
# line 215 "ch_fsm.st"
			printf("Initializing OFF_ON_FSM...\n");
# line 216 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "WAIT...3");
# line 217 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "INIT_4" in state set "OFF_ON_FSM" ******/

/* Event function for state "INIT_4" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_INIT_4(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 221 "ch_fsm.st"
	if (seq_delay(seqg_env, 2))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "INIT_4" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_INIT_4(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 222 "ch_fsm.st"
			seqg_var->flt_clr = 1;
# line 223 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 5/*flt_clr*/, DEFAULT, DEFAULT_TIMEOUT);
# line 224 "ch_fsm.st"
			printf("Initializing OFF_ON_FSM...\n");
# line 225 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "Clearing Faults");
# line 226 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "INIT_5" in state set "OFF_ON_FSM" ******/

/* Event function for state "INIT_5" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_INIT_5(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 230 "ch_fsm.st"
	if (seq_delay(seqg_env, 5))
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "INIT_5" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_INIT_5(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 231 "ch_fsm.st"
			seqg_var->flt_clr = 0;
# line 232 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 5/*flt_clr*/, DEFAULT, DEFAULT_TIMEOUT);
# line 233 "ch_fsm.st"
			printf("Initializing OFF_ON_FSM...\n");
# line 235 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "IDLE" in state set "OFF_ON_FSM" ******/

/* Event function for state "IDLE" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_IDLE(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 243 "ch_fsm.st"
	if (seqg_var->autozero == 1)
	{
		*seqg_pnst = 23;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 257 "ch_fsm.st"
	if (seqg_var->ps_on_off == 1)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 267 "ch_fsm.st"
	if (seqg_var->ps_on_off == 0)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "IDLE" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_IDLE(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 244 "ch_fsm.st"
			seqg_var->atzo_sts = 1;
# line 245 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 27/*atzo_sts*/, DEFAULT, DEFAULT_TIMEOUT);
# line 246 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "Zeroing DCCT Offsets");
# line 247 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
# line 248 "ch_fsm.st"
			seqg_var->avg_mode = 0;
# line 249 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 26/*avg_mode*/, DEFAULT, DEFAULT_TIMEOUT);
# line 250 "ch_fsm.st"
			seqg_var->dcct1_ofst = 0;
# line 251 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 18/*dcct1_ofst*/, DEFAULT, DEFAULT_TIMEOUT);
# line 252 "ch_fsm.st"
			seqg_var->dcct2_ofst = 0;
# line 253 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 20/*dcct2_ofst*/, DEFAULT, DEFAULT_TIMEOUT);
# line 254 "ch_fsm.st"
			seqg_var->dac_ofst = 0;
# line 255 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 23/*dac_ofst*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 258 "ch_fsm.st"
			seqg_var->Park = 1;
# line 259 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 2/*Park*/, DEFAULT, DEFAULT_TIMEOUT);
# line 260 "ch_fsm.st"
			seqg_var->DAC = 0.0;
# line 261 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 0/*DAC*/, DEFAULT, DEFAULT_TIMEOUT);
# line 262 "ch_fsm.st"
			seqg_var->ps_on_off_sts = 0;
# line 263 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 7/*ps_on_off_sts*/, DEFAULT, DEFAULT_TIMEOUT);
# line 264 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "Zeroing DAC");
# line 265 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 2:
		{
# line 269 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "PS OFF");
# line 270 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "CHECK_IF_SYSTEM_WAS_FAULTED" in state set "OFF_ON_FSM" ******/

/* Event function for state "CHECK_IF_SYSTEM_WAS_FAULTED" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_CHECK_IF_SYSTEM_WAS_FAULTED(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 275 "ch_fsm.st"
	if (seqg_var->from_faulted_state == 0)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 279 "ch_fsm.st"
	if (seqg_var->from_faulted_state == 1)
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "CHECK_IF_SYSTEM_WAS_FAULTED" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_CHECK_IF_SYSTEM_WAS_FAULTED(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 276 "ch_fsm.st"
			seqg_var->ps_on_off_sts = 1;
# line 277 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 7/*ps_on_off_sts*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 280 "ch_fsm.st"
			seqg_var->from_faulted_state = 0;
# line 281 "ch_fsm.st"
			seqg_var->Park = 1;
# line 282 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 2/*Park*/, DEFAULT, DEFAULT_TIMEOUT);
# line 283 "ch_fsm.st"
			seqg_var->DAC = 0.0;
# line 284 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 0/*DAC*/, DEFAULT, DEFAULT_TIMEOUT);
# line 285 "ch_fsm.st"
			seqg_var->ps_on_off_sts = 0;
# line 286 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 7/*ps_on_off_sts*/, DEFAULT, DEFAULT_TIMEOUT);
# line 287 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "Zeroing DAC");
# line 288 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "SET_DAC_TO_ZERO_ON" in state set "OFF_ON_FSM" ******/

/* Event function for state "SET_DAC_TO_ZERO_ON" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_SET_DAC_TO_ZERO_ON(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 293 "ch_fsm.st"
	if ((seqg_var->DAC_rdbck < 0.01) && (seqg_var->DAC_rdbck > -0.01))
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "SET_DAC_TO_ZERO_ON" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_SET_DAC_TO_ZERO_ON(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 294 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "Zeroing DAC");
# line 295 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
# line 296 "ch_fsm.st"
			seqg_var->DAC = 0.000;
# line 297 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 0/*DAC*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "CLEAR_FAULTS" in state set "OFF_ON_FSM" ******/

/* Event function for state "CLEAR_FAULTS" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_CLEAR_FAULTS(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 302 "ch_fsm.st"
	if (seq_delay(seqg_env, 2))
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "CLEAR_FAULTS" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_CLEAR_FAULTS(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 303 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "Clearing Faults");
# line 304 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
# line 305 "ch_fsm.st"
			seqg_var->flt_clr = 1;
# line 306 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 5/*flt_clr*/, DEFAULT, DEFAULT_TIMEOUT);
# line 307 "ch_fsm.st"
			seqg_var->ch1_en_cmd = 1;
# line 308 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 11/*ch1_en_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 309 "ch_fsm.st"
			seqg_var->ch2_en_cmd = 1;
# line 310 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 12/*ch2_en_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 311 "ch_fsm.st"
			seqg_var->ch3_en_cmd = 1;
# line 312 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 13/*ch3_en_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 313 "ch_fsm.st"
			seqg_var->ch4_en_cmd = 1;
# line 314 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 14/*ch4_en_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "WAIT_TO_CLEAR" in state set "OFF_ON_FSM" ******/

/* Event function for state "WAIT_TO_CLEAR" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_WAIT_TO_CLEAR(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 318 "ch_fsm.st"
	if (seq_delay(seqg_env, 5))
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "WAIT_TO_CLEAR" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_WAIT_TO_CLEAR(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 319 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "Clearing Faults");
# line 320 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
# line 321 "ch_fsm.st"
			seqg_var->flt_clr = 0;
# line 322 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 5/*flt_clr*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "POWER_ON" in state set "OFF_ON_FSM" ******/

/* Event function for state "POWER_ON" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_POWER_ON(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 326 "ch_fsm.st"
	if (seq_delay(seqg_env, 2))
	{
		*seqg_pnst = 11;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "POWER_ON" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_POWER_ON(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 327 "ch_fsm.st"
			seqg_var->on1_cmd = 1;
# line 328 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 10/*on1_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 329 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "Powering ON");
# line 330 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "PARK_OFF" in state set "OFF_ON_FSM" ******/

/* Event function for state "PARK_OFF" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_PARK_OFF(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 334 "ch_fsm.st"
	if (seq_delay(seqg_env, 8))
	{
		*seqg_pnst = 12;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "PARK_OFF" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_PARK_OFF(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 335 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "Park OFF");
# line 336 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
# line 337 "ch_fsm.st"
			seqg_var->Park = 0;
# line 338 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 2/*Park*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "CHECK_TYPE" in state set "OFF_ON_FSM" ******/

/* Event function for state "CHECK_TYPE" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_CHECK_TYPE(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 342 "ch_fsm.st"
	if (seqg_var->Polarity == 0)
	{
		*seqg_pnst = 13;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 344 "ch_fsm.st"
	if (seqg_var->Polarity == 1)
	{
		*seqg_pnst = 14;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "CHECK_TYPE" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_CHECK_TYPE(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "DONE_CHECK_BIPOLAR" in state set "OFF_ON_FSM" ******/

/* Event function for state "DONE_CHECK_BIPOLAR" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_DONE_CHECK_BIPOLAR(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 348 "ch_fsm.st"
	if (seqg_var->ps_on_sts_bip == 0)
	{
		*seqg_pnst = 15;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 353 "ch_fsm.st"
	if (seqg_var->ps_on_sts_bip == 1)
	{
		*seqg_pnst = 17;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "DONE_CHECK_BIPOLAR" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_DONE_CHECK_BIPOLAR(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 350 "ch_fsm.st"
			seqg_var->ps_on_off_sts = 0;
# line 351 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 7/*ps_on_off_sts*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "DONE_CHECK_UNIPOLAR" in state set "OFF_ON_FSM" ******/

/* Event function for state "DONE_CHECK_UNIPOLAR" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_DONE_CHECK_UNIPOLAR(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 357 "ch_fsm.st"
	if (seqg_var->ps_on_sts_uni == 0)
	{
		*seqg_pnst = 15;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 362 "ch_fsm.st"
	if (seqg_var->ps_on_sts_uni == 1)
	{
		*seqg_pnst = 17;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "DONE_CHECK_UNIPOLAR" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_DONE_CHECK_UNIPOLAR(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 359 "ch_fsm.st"
			seqg_var->ps_on_off_sts = 0;
# line 360 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 7/*ps_on_off_sts*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "RETRY_ON" in state set "OFF_ON_FSM" ******/

/* Event function for state "RETRY_ON" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_RETRY_ON(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 366 "ch_fsm.st"
	if (seqg_var->ps_on_off == 0)
	{
		*seqg_pnst = 16;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "RETRY_ON" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_RETRY_ON(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 367 "ch_fsm.st"
			seqg_var->ps_on_off_sts = 2;
# line 368 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 7/*ps_on_off_sts*/, DEFAULT, DEFAULT_TIMEOUT);
# line 369 "ch_fsm.st"
			seqg_var->on1_cmd = 0;
# line 370 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 10/*on1_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 371 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "Faulted..Try Again");
# line 372 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "RETRY_IDLE" in state set "OFF_ON_FSM" ******/

/* Event function for state "RETRY_IDLE" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_RETRY_IDLE(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 376 "ch_fsm.st"
	if (seqg_var->ps_on_off == 1)
	{
		*seqg_pnst = 0;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "RETRY_IDLE" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_RETRY_IDLE(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 377 "ch_fsm.st"
			seqg_var->ps_on_off_sts = 2;
# line 378 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 7/*ps_on_off_sts*/, DEFAULT, DEFAULT_TIMEOUT);
# line 379 "ch_fsm.st"
			seqg_var->on1_cmd = 0;
# line 380 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 10/*on1_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 381 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "Faulted..Try Again");
# line 382 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "DONE" in state set "OFF_ON_FSM" ******/

/* Event function for state "DONE" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_DONE(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 386 "ch_fsm.st"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "DONE" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_DONE(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 387 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, " PS Ready!");
# line 388 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
# line 389 "ch_fsm.st"
			seqg_var->ps_on_off_sts = 1;
# line 390 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 7/*ps_on_off_sts*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "READY" in state set "OFF_ON_FSM" ******/

/* Event function for state "READY" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_READY(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 394 "ch_fsm.st"
	if (seqg_var->ps_on_off == 1)
	{
		*seqg_pnst = 20;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 402 "ch_fsm.st"
	if (seqg_var->ps_on_off == 0)
	{
		*seqg_pnst = 19;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "READY" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_READY(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 395 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "Zeroing DAC");
# line 396 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
# line 397 "ch_fsm.st"
			seqg_var->DAC = 0.00;
# line 398 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 0/*DAC*/, DEFAULT, DEFAULT_TIMEOUT);
# line 399 "ch_fsm.st"
			seqg_var->ps_on_off_sts = 0;
# line 400 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 7/*ps_on_off_sts*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 403 "ch_fsm.st"
			seqg_var->ps_on_off_sts = 1;
# line 404 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 7/*ps_on_off_sts*/, DEFAULT, DEFAULT_TIMEOUT);
# line 405 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, " PS Ready!");
# line 406 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "CHECK_FAULT" in state set "OFF_ON_FSM" ******/

/* Event function for state "CHECK_FAULT" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_CHECK_FAULT(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 410 "ch_fsm.st"
	if (seqg_var->sum_fault == 0)
	{
		*seqg_pnst = 18;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 412 "ch_fsm.st"
	if (seqg_var->sum_fault > 0)
	{
		*seqg_pnst = 15;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "CHECK_FAULT" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_CHECK_FAULT(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 413 "ch_fsm.st"
			seqg_var->from_faulted_state = 1;
# line 414 "ch_fsm.st"
			seqg_var->ps_on_off_sts = 2;
# line 415 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 7/*ps_on_off_sts*/, DEFAULT, DEFAULT_TIMEOUT);
# line 416 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "Faulted..Try Again");
		}
		return;
	}
}

/****** Code for state "SET_DAC_TO_ZERO_OFF" in state set "OFF_ON_FSM" ******/

/* Event function for state "SET_DAC_TO_ZERO_OFF" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_SET_DAC_TO_ZERO_OFF(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 420 "ch_fsm.st"
	if ((seqg_var->DAC_rdbck < 0.01) && (seqg_var->DAC_rdbck > -0.05))
	{
		*seqg_pnst = 21;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "SET_DAC_TO_ZERO_OFF" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_SET_DAC_TO_ZERO_OFF(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 421 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "Turning OFF");
# line 422 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "POWER_OFF" in state set "OFF_ON_FSM" ******/

/* Event function for state "POWER_OFF" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_POWER_OFF(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 426 "ch_fsm.st"
	if (seq_delay(seqg_env, 5))
	{
		*seqg_pnst = 22;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "POWER_OFF" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_POWER_OFF(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 427 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "Turning OFF");
# line 428 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
# line 429 "ch_fsm.st"
			seqg_var->on1_cmd = 0;
# line 430 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 10/*on1_cmd*/, DEFAULT, DEFAULT_TIMEOUT);
# line 431 "ch_fsm.st"
			seqg_var->Park = 1;
# line 432 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 2/*Park*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "COMPLETE" in state set "OFF_ON_FSM" ******/

/* Event function for state "COMPLETE" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_COMPLETE(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 436 "ch_fsm.st"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "COMPLETE" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_COMPLETE(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 437 "ch_fsm.st"
			sprintf(seqg_var->Chan_seq_messages, "Power OFF");
# line 438 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 28/*Chan_seq_messages*/, DEFAULT, DEFAULT_TIMEOUT);
# line 439 "ch_fsm.st"
			seqg_var->ps_on_off_sts = 1;
# line 440 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 7/*ps_on_off_sts*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "READBACK_DCCT1_ADC_OFFSET" in state set "OFF_ON_FSM" ******/

/* Event function for state "READBACK_DCCT1_ADC_OFFSET" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_READBACK_DCCT1_ADC_OFFSET(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 448 "ch_fsm.st"
	if (seq_delay(seqg_env, 3))
	{
		*seqg_pnst = 25;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "READBACK_DCCT1_ADC_OFFSET" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_READBACK_DCCT1_ADC_OFFSET(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 449 "ch_fsm.st"
			seq_pvGetTmo(seqg_env, 17/*dcct1_adc*/, DEFAULT, DEFAULT_TIMEOUT);
# line 450 "ch_fsm.st"
			seqg_var->dcct1_ofst = seqg_var->dcct1_adc;
# line 451 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 18/*dcct1_ofst*/, DEFAULT, DEFAULT_TIMEOUT);
# line 452 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "%f Offset", seqg_var->dcct1_adc);
# line 453 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "WAIT1" in state set "OFF_ON_FSM" ******/

/* Event function for state "WAIT1" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_WAIT1(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 457 "ch_fsm.st"
	if (seq_delay(seqg_env, 4))
	{
		*seqg_pnst = 25;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "WAIT1" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_WAIT1(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "CHECK_DCCT1" in state set "OFF_ON_FSM" ******/

/* Event function for state "CHECK_DCCT1" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_CHECK_DCCT1(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 461 "ch_fsm.st"
	if (seqg_var->dcct1_adc < fabs(seqg_env, 0.001))
	{
		*seqg_pnst = 26;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 465 "ch_fsm.st"
	if (seqg_var->dcct1_adc > fabs(seqg_env, 0.001))
	{
		*seqg_pnst = 23;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "CHECK_DCCT1" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_CHECK_DCCT1(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 462 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "DCCT1 GOOD");
# line 463 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 466 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "DCCT1 RETRY");
# line 467 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "READBACK_DCCT2_ADC_OFFSET" in state set "OFF_ON_FSM" ******/

/* Event function for state "READBACK_DCCT2_ADC_OFFSET" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_READBACK_DCCT2_ADC_OFFSET(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 471 "ch_fsm.st"
	if (4)
	{
		*seqg_pnst = 27;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "READBACK_DCCT2_ADC_OFFSET" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_READBACK_DCCT2_ADC_OFFSET(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 472 "ch_fsm.st"
			seq_pvGetTmo(seqg_env, 19/*dcct2_adc*/, DEFAULT, DEFAULT_TIMEOUT);
# line 473 "ch_fsm.st"
			seqg_var->dcct2_ofst = seqg_var->dcct2_adc;
# line 474 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 20/*dcct2_ofst*/, DEFAULT, DEFAULT_TIMEOUT);
# line 475 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "%f Offset", seqg_var->dcct2_adc);
# line 476 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "WAIT2" in state set "OFF_ON_FSM" ******/

/* Event function for state "WAIT2" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_WAIT2(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 480 "ch_fsm.st"
	if (seq_delay(seqg_env, 3))
	{
		*seqg_pnst = 28;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "WAIT2" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_WAIT2(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "CHECK_DCCT2" in state set "OFF_ON_FSM" ******/

/* Event function for state "CHECK_DCCT2" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_CHECK_DCCT2(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 484 "ch_fsm.st"
	if (seqg_var->dcct2_adc < fabs(seqg_env, 0.001))
	{
		*seqg_pnst = 29;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 488 "ch_fsm.st"
	if (seqg_var->dcct2_adc > fabs(seqg_env, 0.001))
	{
		*seqg_pnst = 26;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "CHECK_DCCT2" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_CHECK_DCCT2(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 485 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "DCCT2 GOOD");
# line 486 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 489 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "DCCT2 RETRY");
# line 490 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "JUMP_MODE" in state set "OFF_ON_FSM" ******/

/* Event function for state "JUMP_MODE" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_JUMP_MODE(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 30;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "JUMP_MODE" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_JUMP_MODE(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 495 "ch_fsm.st"
			seqg_var->mode = 3;
# line 496 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 21/*mode*/, DEFAULT, DEFAULT_TIMEOUT);
# line 497 "ch_fsm.st"
			seqg_var->avg_mode = 1;
# line 498 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 26/*avg_mode*/, DEFAULT, DEFAULT_TIMEOUT);
# line 499 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "DAC ADJUSTMENT");
# line 500 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "WAIT3" in state set "OFF_ON_FSM" ******/

/* Event function for state "WAIT3" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_WAIT3(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 504 "ch_fsm.st"
	if (seq_delay(seqg_env, 3))
	{
		*seqg_pnst = 31;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "WAIT3" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_WAIT3(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 505 "ch_fsm.st"
			seqg_var->timeout_count = 0;
# line 506 "ch_fsm.st"
			seq_pvGetTmo(seqg_env, 22/*error_adc*/, DEFAULT, DEFAULT_TIMEOUT);
# line 507 "ch_fsm.st"
			seqg_var->error_old = fabs(seqg_env, seqg_var->error_adc);
		}
		return;
	}
}

/****** Code for state "INCREMENT_UP" in state set "OFF_ON_FSM" ******/

/* Event function for state "INCREMENT_UP" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_INCREMENT_UP(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 511 "ch_fsm.st"
	if (fabs(seqg_env, seqg_var->error_adc) < 0.01)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 520 "ch_fsm.st"
	if (fabs(seqg_env, seqg_var->error_adc) > 0.01)
	{
		*seqg_pnst = 33;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "INCREMENT_UP" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_INCREMENT_UP(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 512 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 23/*dac_ofst*/, DEFAULT, DEFAULT_TIMEOUT);
# line 513 "ch_fsm.st"
			seqg_var->mode = 0;
# line 514 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 21/*mode*/, DEFAULT, DEFAULT_TIMEOUT);
# line 515 "ch_fsm.st"
			seqg_var->atzo_sts = 0;
# line 516 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 27/*atzo_sts*/, DEFAULT, DEFAULT_TIMEOUT);
# line 517 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "COMPLETE");
# line 518 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 521 "ch_fsm.st"
			seqg_var->up = 1;
# line 522 "ch_fsm.st"
			if (seqg_var->res == 0)
			{
# line 523 "ch_fsm.st"
				seqg_var->dac_ofst = seqg_var->dac_ofst + (RES_M * seqg_var->scale_factor);
			}
			else
			{
# line 526 "ch_fsm.st"
				seqg_var->dac_ofst = seqg_var->dac_ofst + (RES_H * seqg_var->scale_factor);
			}
# line 528 "ch_fsm.st"
			seqg_var->timeout_count = seqg_var->timeout_count + 1;
# line 529 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 23/*dac_ofst*/, DEFAULT, DEFAULT_TIMEOUT);
# line 530 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "GOING UP");
# line 531 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "INCREMENT_DOWN" in state set "OFF_ON_FSM" ******/

/* Event function for state "INCREMENT_DOWN" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_INCREMENT_DOWN(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 535 "ch_fsm.st"
	if (fabs(seqg_env, seqg_var->error_adc) < 0.01)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 547 "ch_fsm.st"
	if (fabs(seqg_env, seqg_var->error_adc) > 0.01)
	{
		*seqg_pnst = 33;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "INCREMENT_DOWN" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_INCREMENT_DOWN(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 536 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 23/*dac_ofst*/, DEFAULT, DEFAULT_TIMEOUT);
# line 537 "ch_fsm.st"
			seqg_var->mode = 0;
# line 538 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 21/*mode*/, DEFAULT, DEFAULT_TIMEOUT);
# line 539 "ch_fsm.st"
			seqg_var->timeout_count = 0;
# line 540 "ch_fsm.st"
			seqg_var->mode = 0;
# line 541 "ch_fsm.st"
			seqg_var->atzo_sts = 0;
# line 542 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 27/*atzo_sts*/, DEFAULT, DEFAULT_TIMEOUT);
# line 543 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 21/*mode*/, DEFAULT, DEFAULT_TIMEOUT);
# line 544 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "COMPLETE");
# line 545 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 548 "ch_fsm.st"
			seqg_var->timeout_count = seqg_var->timeout_count + 1;
# line 549 "ch_fsm.st"
			if (seqg_var->res == 0)
			{
# line 550 "ch_fsm.st"
				seqg_var->dac_ofst = seqg_var->dac_ofst - (RES_M * seqg_var->scale_factor);
			}
			else
			{
# line 552 "ch_fsm.st"
				seqg_var->dac_ofst = seqg_var->dac_ofst - (RES_H * seqg_var->scale_factor);
			}
# line 555 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 23/*dac_ofst*/, DEFAULT, DEFAULT_TIMEOUT);
# line 556 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "GOING DOWN");
# line 557 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "WAIT4" in state set "OFF_ON_FSM" ******/

/* Event function for state "WAIT4" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_WAIT4(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 561 "ch_fsm.st"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 34;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "WAIT4" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_WAIT4(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 562 "ch_fsm.st"
			seq_pvGetTmo(seqg_env, 22/*error_adc*/, DEFAULT, DEFAULT_TIMEOUT);
# line 563 "ch_fsm.st"
			seqg_var->error_new = fabs(seqg_env, seqg_var->error_adc);
# line 564 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "WAIT.. ");
# line 565 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "WAIT5" in state set "OFF_ON_FSM" ******/

/* Event function for state "WAIT5" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_WAIT5(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 569 "ch_fsm.st"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 35;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "WAIT5" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_WAIT5(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 570 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "WAIT....");
# line 571 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "VOTE_CHECK" in state set "OFF_ON_FSM" ******/

/* Event function for state "VOTE_CHECK" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_VOTE_CHECK(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 575 "ch_fsm.st"
	if (seqg_var->check_count == 3)
	{
		*seqg_pnst = 37;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 577 "ch_fsm.st"
	if (seqg_var->check_count < 3)
	{
		*seqg_pnst = 36;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "VOTE_CHECK" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_VOTE_CHECK(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 578 "ch_fsm.st"
			if (seqg_var->error_new < seqg_var->error_old)
			{
# line 579 "ch_fsm.st"
				seqg_var->down_vote = seqg_var->down_vote + 1;
			}
			else
			{
# line 581 "ch_fsm.st"
				seqg_var->up_vote = seqg_var->up_vote + 1;
			}
# line 583 "ch_fsm.st"
			seqg_var->check_count = seqg_var->check_count + 1;
# line 584 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "WAIT....");
# line 585 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "RECHECK_ERROR_ADC" in state set "OFF_ON_FSM" ******/

/* Event function for state "RECHECK_ERROR_ADC" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_RECHECK_ERROR_ADC(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 589 "ch_fsm.st"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 35;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "RECHECK_ERROR_ADC" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_RECHECK_ERROR_ADC(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 590 "ch_fsm.st"
			seq_pvGetTmo(seqg_env, 22/*error_adc*/, DEFAULT, DEFAULT_TIMEOUT);
# line 591 "ch_fsm.st"
			seqg_var->error_new = fabs(seqg_env, seqg_var->error_adc);
		}
		return;
	}
}

/****** Code for state "WAIT8" in state set "OFF_ON_FSM" ******/

/* Event function for state "WAIT8" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_WAIT8(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 595 "ch_fsm.st"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 38;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "WAIT8" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_WAIT8(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "CHECK_NEW_ERROR" in state set "OFF_ON_FSM" ******/

/* Event function for state "CHECK_NEW_ERROR" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_CHECK_NEW_ERROR(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 599 "ch_fsm.st"
	if (seqg_var->timeout_count > 50)
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 608 "ch_fsm.st"
	if (seqg_var->up_vote > seqg_var->down_vote)
	{
		*seqg_pnst = 39;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 619 "ch_fsm.st"
	if (seqg_var->down_vote > seqg_var->up_vote)
	{
		*seqg_pnst = 39;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "CHECK_NEW_ERROR" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_CHECK_NEW_ERROR(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 600 "ch_fsm.st"
			seqg_var->timeout_count = 0;
# line 601 "ch_fsm.st"
			seqg_var->atzo_sts = 0;
# line 602 "ch_fsm.st"
			seqg_var->mode = 0;
# line 603 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 21/*mode*/, DEFAULT, DEFAULT_TIMEOUT);
# line 604 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 27/*atzo_sts*/, DEFAULT, DEFAULT_TIMEOUT);
# line 605 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "NON-CONVERGENT!");
# line 606 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 609 "ch_fsm.st"
			seqg_var->check_count = 0;
# line 610 "ch_fsm.st"
			seqg_var->up_vote = 0;
# line 611 "ch_fsm.st"
			seqg_var->down_vote = 0;
# line 612 "ch_fsm.st"
			if (seqg_var->up = 1)
			{
# line 613 "ch_fsm.st"
				seqg_var->up = 0;
			}
			else
			{
# line 615 "ch_fsm.st"
				seqg_var->up = 1;
			}
# line 616 "ch_fsm.st"
			;
# line 617 "ch_fsm.st"
			seqg_var->error_old = seqg_var->error_new;
		}
		return;
	case 2:
		{
# line 620 "ch_fsm.st"
			seqg_var->check_count = 0;
# line 621 "ch_fsm.st"
			seqg_var->up_vote = 0;
# line 622 "ch_fsm.st"
			seqg_var->down_vote = 0;
# line 623 "ch_fsm.st"
			seqg_var->up = seqg_var->up;
# line 624 "ch_fsm.st"
			seqg_var->error_old = seqg_var->error_new;
		}
		return;
	}
}

/****** Code for state "WAIT7" in state set "OFF_ON_FSM" ******/

/* Event function for state "WAIT7" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_WAIT7(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 628 "ch_fsm.st"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 40;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "WAIT7" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_WAIT7(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 629 "ch_fsm.st"
			seqg_var->error_new = fabs(seqg_env, seq_pvGetTmo(seqg_env, 22/*error_adc*/, DEFAULT, DEFAULT_TIMEOUT));
		}
		return;
	}
}

/****** Code for state "UP_DOWN" in state set "OFF_ON_FSM" ******/

/* Event function for state "UP_DOWN" in state set "OFF_ON_FSM" */
static seqBool seqg_event_OFF_ON_FSM_0_UP_DOWN(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 633 "ch_fsm.st"
	if (seqg_var->up > 0)
	{
		*seqg_pnst = 31;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 637 "ch_fsm.st"
	if (seqg_var->up == 0)
	{
		*seqg_pnst = 32;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "UP_DOWN" in state set "OFF_ON_FSM" */
static void seqg_action_OFF_ON_FSM_0_UP_DOWN(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 634 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "ZERO CHECK");
# line 635 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
# line 638 "ch_fsm.st"
			sprintf(seqg_var->atzo_messages, "ZERO CHECK");
# line 639 "ch_fsm.st"
			seq_pvPutTmo(seqg_env, 29/*atzo_messages*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{M0}{M1}:DAC_SetPt-SP", offsetof(struct seqg_vars, DAC), "DAC", P_SHORT, 1, 1, 0, 1, 0, 0},
	{"{M0}{M1}:DAC-I", offsetof(struct seqg_vars, DAC_rdbck), "DAC_rdbck", P_SHORT, 1, 2, 0, 1, 0, 0},
	{"{M0}{M1}:DigOut_Park-SP", offsetof(struct seqg_vars, Park), "Park", P_SHORT, 1, 3, 0, 1, 0, 0},
	{"{M0}Polarity-Mode", offsetof(struct seqg_vars, Polarity), "Polarity", P_SHORT, 1, 4, 0, 1, 0, 0},
	{"{M0}{M1}:FaultMask:B12-SP", offsetof(struct seqg_vars, flt_mask), "flt_mask", P_SHORT, 1, 5, 0, 1, 0, 0},
	{"{M0}{M1}:FaultClear-SP", offsetof(struct seqg_vars, flt_clr), "flt_clr", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{M0}{M1}:PSOnOff-SP", offsetof(struct seqg_vars, ps_on_off), "ps_on_off", P_SHORT, 1, 7, 0, 1, 0, 0},
	{"{M0}{M1}:PSOnOff-STS", offsetof(struct seqg_vars, ps_on_off_sts), "ps_on_off_sts", P_SHORT, 1, 8, 0, 1, 0, 0},
	{"{M0}{M1}:DigIn-I.B0", offsetof(struct seqg_vars, ps_on_sts_bip), "ps_on_sts_bip", P_SHORT, 1, 9, 0, 1, 0, 0},
	{"{M0}{M1}:DigIn-I.B1", offsetof(struct seqg_vars, ps_on_sts_uni), "ps_on_sts_uni", P_SHORT, 1, 10, 0, 1, 0, 0},
	{"{M0}{M1}:DigOut_ON1-SP", offsetof(struct seqg_vars, on1_cmd), "on1_cmd", P_SHORT, 1, 11, 0, 0, 0, 0},
	{"{M0}Chan1:DigOut_ON2-SP", offsetof(struct seqg_vars, ch1_en_cmd), "ch1_en_cmd", P_SHORT, 1, 12, 0, 1, 0, 0},
	{"{M0}Chan2:DigOut_ON2-SP", offsetof(struct seqg_vars, ch2_en_cmd), "ch2_en_cmd", P_SHORT, 1, 13, 0, 1, 0, 0},
	{"{M0}Chan3:DigOut_ON2-SP", offsetof(struct seqg_vars, ch3_en_cmd), "ch3_en_cmd", P_SHORT, 1, 14, 0, 1, 0, 0},
	{"{M0}Chan4:DigOut_ON2-SP", offsetof(struct seqg_vars, ch4_en_cmd), "ch4_en_cmd", P_SHORT, 1, 15, 0, 1, 0, 0},
	{"{M0}{M1}:FaultsLat-I", offsetof(struct seqg_vars, sum_fault), "sum_fault", P_SHORT, 1, 16, 0, 1, 0, 0},
	{"{M0}{M1}:AutoZero-SP", offsetof(struct seqg_vars, autozero), "autozero", P_SHORT, 1, 17, 0, 1, 0, 0},
	{"{M0}{M1}:DCCT1-I", offsetof(struct seqg_vars, dcct1_adc), "dcct1_adc", P_DOUBLE, 1, 18, 0, 1, 0, 0},
	{"{M0}{M1}:DCCT1-Offset-SP", offsetof(struct seqg_vars, dcct1_ofst), "dcct1_ofst", P_DOUBLE, 1, 19, 0, 1, 0, 0},
	{"{M0}{M1}:DCCT2-I", offsetof(struct seqg_vars, dcct2_adc), "dcct2_adc", P_DOUBLE, 1, 20, 0, 1, 0, 0},
	{"{M0}{M1}:DCCT2-Offset-SP", offsetof(struct seqg_vars, dcct2_ofst), "dcct2_ofst", P_DOUBLE, 1, 21, 0, 1, 0, 0},
	{"{M0}{M1}:DAC_OpMode-SP", offsetof(struct seqg_vars, mode), "mode", P_SHORT, 1, 22, 0, 1, 0, 0},
	{"{M0}{M1}:Error-I", offsetof(struct seqg_vars, error_adc), "error_adc", P_DOUBLE, 1, 23, 0, 1, 0, 0},
	{"{M0}{M1}:DACSetPt-Offset-SP", offsetof(struct seqg_vars, dac_ofst), "dac_ofst", P_DOUBLE, 1, 24, 0, 1, 0, 0},
	{"{M0}{M1}:SF:DAC_DCCTs-I", offsetof(struct seqg_vars, scale_factor), "scale_factor", P_DOUBLE, 1, 25, 0, 1, 0, 0},
	{"{M0}Resolution-Mode", offsetof(struct seqg_vars, res), "res", P_SHORT, 1, 26, 0, 1, 0, 0},
	{"{M0}{M1}:AveMode-SP", offsetof(struct seqg_vars, avg_mode), "avg_mode", P_SHORT, 1, 27, 0, 1, 0, 0},
	{"{M0}{M1}:AutoZero-STS", offsetof(struct seqg_vars, atzo_sts), "atzo_sts", P_SHORT, 1, 28, 0, 1, 0, 0},
	{"{M0}{M1}_seq_messages", offsetof(struct seqg_vars, Chan_seq_messages), "Chan_seq_messages", P_STRING, 1, 29, 0, 0, 0, 0},
	{"{M0}{M1}_atzo_messages", offsetof(struct seqg_vars, atzo_messages), "atzo_messages", P_STRING, 1, 30, 0, 0, 0, 0},
	{"{M0}{M1}_atzo_dbg1_messages", offsetof(struct seqg_vars, atzo_dbg1_messages), "atzo_dbg1_messages", P_STRING, 1, 31, 0, 0, 0, 0},
	{"{M0}{M1}_atzo_dbg2_messages", offsetof(struct seqg_vars, atzo_dbg2_messages), "atzo_dbg2_messages", P_STRING, 1, 32, 0, 0, 0, 0},
	{"{M0}{M1}_atzo_dbg3_messages", offsetof(struct seqg_vars, atzo_dbg3_messages), "atzo_dbg3_messages", P_STRING, 1, 33, 0, 0, 0, 0},
};

/* Event masks for state set "OFF_ON_FSM" */
static const seqMask seqg_mask_OFF_ON_FSM_0_INIT_1[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_INIT_2[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_INIT_3[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_INIT_4[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_INIT_5[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_IDLE[] = {
	0x00020080,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_CHECK_IF_SYSTEM_WAS_FAULTED[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_SET_DAC_TO_ZERO_ON[] = {
	0x00000004,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_CLEAR_FAULTS[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_WAIT_TO_CLEAR[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_POWER_ON[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_PARK_OFF[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_CHECK_TYPE[] = {
	0x00000010,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_DONE_CHECK_BIPOLAR[] = {
	0x00000200,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_DONE_CHECK_UNIPOLAR[] = {
	0x00000400,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_RETRY_ON[] = {
	0x00000080,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_RETRY_IDLE[] = {
	0x00000080,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_DONE[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_READY[] = {
	0x00000080,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_CHECK_FAULT[] = {
	0x00010000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_SET_DAC_TO_ZERO_OFF[] = {
	0x00000004,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_POWER_OFF[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_COMPLETE[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_READBACK_DCCT1_ADC_OFFSET[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_WAIT1[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_CHECK_DCCT1[] = {
	0x00040000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_READBACK_DCCT2_ADC_OFFSET[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_WAIT2[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_CHECK_DCCT2[] = {
	0x00100000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_JUMP_MODE[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_WAIT3[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_INCREMENT_UP[] = {
	0x00800000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_INCREMENT_DOWN[] = {
	0x00800000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_WAIT4[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_WAIT5[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_VOTE_CHECK[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_RECHECK_ERROR_ADC[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_WAIT8[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_CHECK_NEW_ERROR[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_WAIT7[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_OFF_ON_FSM_0_UP_DOWN[] = {
	0x00000000,
	0x00000000,
};

/* State table for state set "OFF_ON_FSM" */
static seqState seqg_states_OFF_ON_FSM[] = {
	{
	/* state name */        "INIT_1",
	/* action function */   seqg_action_OFF_ON_FSM_0_INIT_1,
	/* event function */    seqg_event_OFF_ON_FSM_0_INIT_1,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_INIT_1,
	/* state options */     (0)
	},
	{
	/* state name */        "INIT_2",
	/* action function */   seqg_action_OFF_ON_FSM_0_INIT_2,
	/* event function */    seqg_event_OFF_ON_FSM_0_INIT_2,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_INIT_2,
	/* state options */     (0)
	},
	{
	/* state name */        "INIT_3",
	/* action function */   seqg_action_OFF_ON_FSM_0_INIT_3,
	/* event function */    seqg_event_OFF_ON_FSM_0_INIT_3,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_INIT_3,
	/* state options */     (0)
	},
	{
	/* state name */        "INIT_4",
	/* action function */   seqg_action_OFF_ON_FSM_0_INIT_4,
	/* event function */    seqg_event_OFF_ON_FSM_0_INIT_4,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_INIT_4,
	/* state options */     (0)
	},
	{
	/* state name */        "INIT_5",
	/* action function */   seqg_action_OFF_ON_FSM_0_INIT_5,
	/* event function */    seqg_event_OFF_ON_FSM_0_INIT_5,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_INIT_5,
	/* state options */     (0)
	},
	{
	/* state name */        "IDLE",
	/* action function */   seqg_action_OFF_ON_FSM_0_IDLE,
	/* event function */    seqg_event_OFF_ON_FSM_0_IDLE,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_IDLE,
	/* state options */     (0)
	},
	{
	/* state name */        "CHECK_IF_SYSTEM_WAS_FAULTED",
	/* action function */   seqg_action_OFF_ON_FSM_0_CHECK_IF_SYSTEM_WAS_FAULTED,
	/* event function */    seqg_event_OFF_ON_FSM_0_CHECK_IF_SYSTEM_WAS_FAULTED,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_CHECK_IF_SYSTEM_WAS_FAULTED,
	/* state options */     (0)
	},
	{
	/* state name */        "SET_DAC_TO_ZERO_ON",
	/* action function */   seqg_action_OFF_ON_FSM_0_SET_DAC_TO_ZERO_ON,
	/* event function */    seqg_event_OFF_ON_FSM_0_SET_DAC_TO_ZERO_ON,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_SET_DAC_TO_ZERO_ON,
	/* state options */     (0)
	},
	{
	/* state name */        "CLEAR_FAULTS",
	/* action function */   seqg_action_OFF_ON_FSM_0_CLEAR_FAULTS,
	/* event function */    seqg_event_OFF_ON_FSM_0_CLEAR_FAULTS,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_CLEAR_FAULTS,
	/* state options */     (0)
	},
	{
	/* state name */        "WAIT_TO_CLEAR",
	/* action function */   seqg_action_OFF_ON_FSM_0_WAIT_TO_CLEAR,
	/* event function */    seqg_event_OFF_ON_FSM_0_WAIT_TO_CLEAR,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_WAIT_TO_CLEAR,
	/* state options */     (0)
	},
	{
	/* state name */        "POWER_ON",
	/* action function */   seqg_action_OFF_ON_FSM_0_POWER_ON,
	/* event function */    seqg_event_OFF_ON_FSM_0_POWER_ON,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_POWER_ON,
	/* state options */     (0)
	},
	{
	/* state name */        "PARK_OFF",
	/* action function */   seqg_action_OFF_ON_FSM_0_PARK_OFF,
	/* event function */    seqg_event_OFF_ON_FSM_0_PARK_OFF,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_PARK_OFF,
	/* state options */     (0)
	},
	{
	/* state name */        "CHECK_TYPE",
	/* action function */   seqg_action_OFF_ON_FSM_0_CHECK_TYPE,
	/* event function */    seqg_event_OFF_ON_FSM_0_CHECK_TYPE,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_CHECK_TYPE,
	/* state options */     (0)
	},
	{
	/* state name */        "DONE_CHECK_BIPOLAR",
	/* action function */   seqg_action_OFF_ON_FSM_0_DONE_CHECK_BIPOLAR,
	/* event function */    seqg_event_OFF_ON_FSM_0_DONE_CHECK_BIPOLAR,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_DONE_CHECK_BIPOLAR,
	/* state options */     (0)
	},
	{
	/* state name */        "DONE_CHECK_UNIPOLAR",
	/* action function */   seqg_action_OFF_ON_FSM_0_DONE_CHECK_UNIPOLAR,
	/* event function */    seqg_event_OFF_ON_FSM_0_DONE_CHECK_UNIPOLAR,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_DONE_CHECK_UNIPOLAR,
	/* state options */     (0)
	},
	{
	/* state name */        "RETRY_ON",
	/* action function */   seqg_action_OFF_ON_FSM_0_RETRY_ON,
	/* event function */    seqg_event_OFF_ON_FSM_0_RETRY_ON,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_RETRY_ON,
	/* state options */     (0)
	},
	{
	/* state name */        "RETRY_IDLE",
	/* action function */   seqg_action_OFF_ON_FSM_0_RETRY_IDLE,
	/* event function */    seqg_event_OFF_ON_FSM_0_RETRY_IDLE,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_RETRY_IDLE,
	/* state options */     (0)
	},
	{
	/* state name */        "DONE",
	/* action function */   seqg_action_OFF_ON_FSM_0_DONE,
	/* event function */    seqg_event_OFF_ON_FSM_0_DONE,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_DONE,
	/* state options */     (0)
	},
	{
	/* state name */        "READY",
	/* action function */   seqg_action_OFF_ON_FSM_0_READY,
	/* event function */    seqg_event_OFF_ON_FSM_0_READY,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_READY,
	/* state options */     (0)
	},
	{
	/* state name */        "CHECK_FAULT",
	/* action function */   seqg_action_OFF_ON_FSM_0_CHECK_FAULT,
	/* event function */    seqg_event_OFF_ON_FSM_0_CHECK_FAULT,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_CHECK_FAULT,
	/* state options */     (0)
	},
	{
	/* state name */        "SET_DAC_TO_ZERO_OFF",
	/* action function */   seqg_action_OFF_ON_FSM_0_SET_DAC_TO_ZERO_OFF,
	/* event function */    seqg_event_OFF_ON_FSM_0_SET_DAC_TO_ZERO_OFF,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_SET_DAC_TO_ZERO_OFF,
	/* state options */     (0)
	},
	{
	/* state name */        "POWER_OFF",
	/* action function */   seqg_action_OFF_ON_FSM_0_POWER_OFF,
	/* event function */    seqg_event_OFF_ON_FSM_0_POWER_OFF,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_POWER_OFF,
	/* state options */     (0)
	},
	{
	/* state name */        "COMPLETE",
	/* action function */   seqg_action_OFF_ON_FSM_0_COMPLETE,
	/* event function */    seqg_event_OFF_ON_FSM_0_COMPLETE,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_COMPLETE,
	/* state options */     (0)
	},
	{
	/* state name */        "READBACK_DCCT1_ADC_OFFSET",
	/* action function */   seqg_action_OFF_ON_FSM_0_READBACK_DCCT1_ADC_OFFSET,
	/* event function */    seqg_event_OFF_ON_FSM_0_READBACK_DCCT1_ADC_OFFSET,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_READBACK_DCCT1_ADC_OFFSET,
	/* state options */     (0)
	},
	{
	/* state name */        "WAIT1",
	/* action function */   seqg_action_OFF_ON_FSM_0_WAIT1,
	/* event function */    seqg_event_OFF_ON_FSM_0_WAIT1,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_WAIT1,
	/* state options */     (0)
	},
	{
	/* state name */        "CHECK_DCCT1",
	/* action function */   seqg_action_OFF_ON_FSM_0_CHECK_DCCT1,
	/* event function */    seqg_event_OFF_ON_FSM_0_CHECK_DCCT1,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_CHECK_DCCT1,
	/* state options */     (0)
	},
	{
	/* state name */        "READBACK_DCCT2_ADC_OFFSET",
	/* action function */   seqg_action_OFF_ON_FSM_0_READBACK_DCCT2_ADC_OFFSET,
	/* event function */    seqg_event_OFF_ON_FSM_0_READBACK_DCCT2_ADC_OFFSET,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_READBACK_DCCT2_ADC_OFFSET,
	/* state options */     (0)
	},
	{
	/* state name */        "WAIT2",
	/* action function */   seqg_action_OFF_ON_FSM_0_WAIT2,
	/* event function */    seqg_event_OFF_ON_FSM_0_WAIT2,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_WAIT2,
	/* state options */     (0)
	},
	{
	/* state name */        "CHECK_DCCT2",
	/* action function */   seqg_action_OFF_ON_FSM_0_CHECK_DCCT2,
	/* event function */    seqg_event_OFF_ON_FSM_0_CHECK_DCCT2,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_CHECK_DCCT2,
	/* state options */     (0)
	},
	{
	/* state name */        "JUMP_MODE",
	/* action function */   seqg_action_OFF_ON_FSM_0_JUMP_MODE,
	/* event function */    seqg_event_OFF_ON_FSM_0_JUMP_MODE,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_JUMP_MODE,
	/* state options */     (0)
	},
	{
	/* state name */        "WAIT3",
	/* action function */   seqg_action_OFF_ON_FSM_0_WAIT3,
	/* event function */    seqg_event_OFF_ON_FSM_0_WAIT3,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_WAIT3,
	/* state options */     (0)
	},
	{
	/* state name */        "INCREMENT_UP",
	/* action function */   seqg_action_OFF_ON_FSM_0_INCREMENT_UP,
	/* event function */    seqg_event_OFF_ON_FSM_0_INCREMENT_UP,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_INCREMENT_UP,
	/* state options */     (0)
	},
	{
	/* state name */        "INCREMENT_DOWN",
	/* action function */   seqg_action_OFF_ON_FSM_0_INCREMENT_DOWN,
	/* event function */    seqg_event_OFF_ON_FSM_0_INCREMENT_DOWN,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_INCREMENT_DOWN,
	/* state options */     (0)
	},
	{
	/* state name */        "WAIT4",
	/* action function */   seqg_action_OFF_ON_FSM_0_WAIT4,
	/* event function */    seqg_event_OFF_ON_FSM_0_WAIT4,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_WAIT4,
	/* state options */     (0)
	},
	{
	/* state name */        "WAIT5",
	/* action function */   seqg_action_OFF_ON_FSM_0_WAIT5,
	/* event function */    seqg_event_OFF_ON_FSM_0_WAIT5,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_WAIT5,
	/* state options */     (0)
	},
	{
	/* state name */        "VOTE_CHECK",
	/* action function */   seqg_action_OFF_ON_FSM_0_VOTE_CHECK,
	/* event function */    seqg_event_OFF_ON_FSM_0_VOTE_CHECK,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_VOTE_CHECK,
	/* state options */     (0)
	},
	{
	/* state name */        "RECHECK_ERROR_ADC",
	/* action function */   seqg_action_OFF_ON_FSM_0_RECHECK_ERROR_ADC,
	/* event function */    seqg_event_OFF_ON_FSM_0_RECHECK_ERROR_ADC,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_RECHECK_ERROR_ADC,
	/* state options */     (0)
	},
	{
	/* state name */        "WAIT8",
	/* action function */   seqg_action_OFF_ON_FSM_0_WAIT8,
	/* event function */    seqg_event_OFF_ON_FSM_0_WAIT8,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_WAIT8,
	/* state options */     (0)
	},
	{
	/* state name */        "CHECK_NEW_ERROR",
	/* action function */   seqg_action_OFF_ON_FSM_0_CHECK_NEW_ERROR,
	/* event function */    seqg_event_OFF_ON_FSM_0_CHECK_NEW_ERROR,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_CHECK_NEW_ERROR,
	/* state options */     (0)
	},
	{
	/* state name */        "WAIT7",
	/* action function */   seqg_action_OFF_ON_FSM_0_WAIT7,
	/* event function */    seqg_event_OFF_ON_FSM_0_WAIT7,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_WAIT7,
	/* state options */     (0)
	},
	{
	/* state name */        "UP_DOWN",
	/* action function */   seqg_action_OFF_ON_FSM_0_UP_DOWN,
	/* event function */    seqg_event_OFF_ON_FSM_0_UP_DOWN,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_OFF_ON_FSM_0_UP_DOWN,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "OFF_ON_FSM",
	/* states */            seqg_states_OFF_ON_FSM,
	/* number of states */  41
	},
};

/* Program table (global) */
seqProgram ch_fsm = {
	/* magic number */      2002008,
	/* program name */      "ch_fsm",
	/* channels */          seqg_chans,
	/* num. channels */     33,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "M0=lab{2}, M1=Chan1",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void ch_fsmRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&ch_fsm);
}
epicsExportRegistrar(ch_fsmRegistrar);
